<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RssArticleViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RssArticleViewRepository extends EntityRepository
{
    /**
     * @param int $id
     * @param string $ip
     * @param string $sessionId
     * @return int
     */
    public function count($id, $ip, $sessionId)
    {
        try {
            return $this->getEntityManager()
                        ->createQueryBuilder()
                        ->select('count(views.id)')
                        ->from('AppBundle:RssArticleView', 'views')
                        ->where('views.rssArticle = :id')
                        ->andWhere('views.ip = :ip')
                        ->andWhere('views.sessionId = :session_id')
                        ->setParameters(array(
                            'id'         => $id,
                            'ip'         => $ip,
                            'session_id' => $sessionId
                        ))
                        ->getQuery()
                        ->getSingleScalarResult();
        } catch (\Exception $e) {
            return 0;
        }
    }
}
