<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RssCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RssCategoryRepository extends EntityRepository
{
    /**
     * @param \Knp\Component\Pager\Paginator $paginator
     * @param bool|true $main
     * @param int $page
     * @param int $limit
     * @return mixed
     */
    public function getCategories($paginator, $main = true, $page = 1, $limit = 10)
    {
        $query = $this->getEntityManager()
                      ->createQueryBuilder()
                      ->select('categories.name, categories.alias, categories.count')
                      ->from('AppBundle:RssCategory', 'categories')
                      ->where('categories.deleted = :deleted')
                      ->setParameter('deleted', 0);

        if ($main) {
            $query->andWhere('categories.main = :main')
                  ->setParameter('main', (int) $main)
                  ->orderBy('categories.name', 'asc');
        } else {
            $query->orderBy('categories.count', 'desc');
        }

        return $paginator->paginate($query->getQuery(), $page, $limit);
    }
}
